services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${DATABASE_PASSWORD:-root}"
      MYSQL_DATABASE: root
    ports:
      - "3306:3306"
    volumes:
      - ../mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - ../redis_data:/data
    command: ["redis-server", "--save", "20", "1", "--loglevel", "warning"]

  backend: &backend
    build:
      context: ../..
      dockerfile: Docker/Dev/dockerfile.backend
      args:
        UID: ${UID}
        GID: ${GID}
    user: www-data
    env_file:
      - ../../.env
    ports:
      - "${BACKEND_PORT:-8000}:80"
    volumes:
      - ../../App:/var/www/App
      - ../../Public:/var/www/Public
      - ../app_storage:/var/www/Storage
    depends_on:
      - redis
      - mysql

  frontend:
    build:
      context: ../..
      dockerfile: Docker/Dev/dockerfile.frontend
      args:
        UID: ${UID}
        GID: ${GID}
    user: node
    env_file:
      - ../../.env
    ports:
      - "${FRONTEND_PORT:-8001}:5173"
    volumes:
      - ../../Frontend/src:/app/src:ro