FROM node:22-alpine

ARG UID=1000
ARG GID=1000

RUN apk add --no-cache shadow \
 && groupmod -g ${GID} node \
 && usermod -u ${UID} node \
 && apk del shadow

WORKDIR /app

COPY ./Frontend/package*.json .
RUN npm install

COPY ./Frontend .
COPY ./.env .

EXPOSE 5173

RUN chown -R node:node /app

#DEBUG
#CMD ["tail", "-f", "/dev/null"]

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
