FROM php:8.5-apache

ARG UID=1000
ARG GID=1000

RUN usermod -u ${UID} www-data && groupmod -g ${GID} www-data

COPY Docker/Dev/vhost.conf /etc/apache2/sites-available/000-default.conf

RUN apt-get update \
    && apt-get install -y unzip git nano \
    && apt-get install -y libzip-dev libpng-dev libwebp-dev libjpeg-dev libfreetype-dev \
    && docker-php-ext-configure gd --with-jpeg --with-webp --with-freetype \
    && docker-php-ext-install pdo pdo_mysql zip gd exif \
    && pecl install redis && docker-php-ext-enable redis \
    && curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

RUN a2enmod rewrite


WORKDIR /var/www

COPY ./App ./App
COPY ./Public ./Public
COPY ./composer.json ./composer.json
COPY ./composer.lock ./composer.lock
COPY ./do ./do
COPY ./cube.php ./cube.php

RUN composer install \
    && chown -R www-data:www-data /var/www

EXPOSE 80
CMD ["apache2-foreground"]
