services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${DATABASE_PASSWORD:-root}"
      MYSQL_DATABASE: root
    ports:
      - "3306:3306"
    volumes:
      - ../mysql_data:/var/lib/mysql
    networks:
      - private
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ../redis_data:/data
    command: ["redis-server", "--save", "20", "1", "--loglevel", "warning"]
    networks:
      - private

  application: &application
    build:
      context: ../..
      dockerfile: Docker/Prod/dockerfile.application
      args:
        UID: ${UID}
        GID: ${GID}
    user: "${UID}:${GID}"
    volumes:
      - ../app_storage:/app/Storage
      - app_sessions:/var/lib/php/sessions
    env_file:
      - ../../.env
    networks:
      - public
      - private
    depends_on:
      - redis
      - mysql
  server:
    image: nginx:alpine
    env_file:
      - ../../.env
    ports:
      - "${APPLICATION_PORT:-8080}:80"
    volumes:
      - ./apcu-nginx-vhost.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - application
    networks:
      - public

volumes:
  app_sessions:

networks:
  public:
  private:
    internal: true