<?php

namespace App\Models;

use Cube\Data\Models\Model;
use Cube\Data\Models\ModelField;
use Cube\Data\Models\Relations\HasMany;
use Cube\Data\Models\Relations\HasOne;
use Cube\Utils\Attributes\Generated;

/**
 * Generated by `Cube\Data\Models\ModelGenerator\Table`
 * @property int $id
 * @property string $name
 * @property string $created_at

 */
class __cubeMigration extends Model
{

    #[Generated]
    public static function table(): string
    {
        return '__cube_migration';
    }

    #[Generated]
    public static function primaryKey(): string
    {
        return 'id';
    }

    /**
     * @return array<string,ModelField>
     */
    #[Generated]
    public static function fields(): array
    {
        return [
            'id' => (new ModelField('id'))->type('INTEGER')->autoIncrement()->notNull()->hasDefault(false),
            'name' => (new ModelField('name'))->type('STRING')->notNull()->hasDefault(false),
            'created_at' => (new ModelField('created_at'))->type('TIMESTAMP')->nullable()->hasDefault(true)->generated()
        ];
    }

    #[Generated]
    public static function relations(): array
    {
        return [
        ];
    }

}