<?php

namespace App\Models;

use Cube\Data\Models\Model;
use Cube\Data\Models\ModelField;
use Cube\Data\Models\Relations\HasMany;
use Cube\Data\Models\Relations\HasOne;
use Cube\Env\Storage;
use Cube\Utils\Attributes\Generated;

/**
 * Generated by `Cube\Data\Models\ModelGenerator\Table`
 * @property string $uuid
 * @property string $path
 * @property string $password_hash

 */
class Directory extends Model
{

    #[Generated]
    public static function table(): string
    {
        return 'directory';
    }

    #[Generated]
    public static function primaryKey(): string
    {
        return 'uuid';
    }

    /**
     * @return array<string,ModelField>
     */
    #[Generated]
    public static function fields(): array
    {
        return [
            'uuid' => (new ModelField('uuid'))->type('STRING')->notNull()->hasDefault(true)->generated(),
            'path' => (new ModelField('path'))->type('STRING')->notNull()->hasDefault(false),
            'password_hash' => (new ModelField('password_hash'))->type('STRING')->nullable()->hasDefault(true)
        ];
    }

    #[Generated]
    public static function relations(): array
    {
        return [
        ];
    }


    public function toStorage(): Storage
    {
        return new Storage($this->path);
    }

}